// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aorftirebmcagwbhoxkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvcmZ0aXJlYm1jYWd3YmhveGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNjQ3NzEsImV4cCI6MjA1Mzc0MDc3MX0.XFX0HW35TFDLQD3rN9CNhpD3KI9eFzSOV_rcvrF-u2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);